// ====================================================================
// 📊 [OMD-CORE-Icons-0001] icons/index.ts ➔ Icons Registry
// 🎯 @KICK  : Onrivi Author 전체 애플리케이션의 아이콘을 중앙 집중식으로 관리하는 통합 레지스트리
// 🛡️ @GUARD : Lucide React 기반의 벡터 일관성, strokeWidth 일원화, 트리 셰이킹 지원
// 🚨 @PATCH : 2026-09-12 — [3D 입체 컬러 아이콘 시스템 구축] 툴바 및 플로팅 툴바 전용 입체감(Depth)과 테마 컬러 매핑(ICON_THEMES) 및 Footnote(Superscript) 탑재
// 🚨 @PATCH : 2026-09-12 — [통합 아이콘 시스템 구축] 이모지 및 개별 icon 분산을 해소하고 의미론적(Semantic) 아이콘 레지스트리 신규 탑재
// 🔗 @CALLS : lucide-react
// ====================================================================
import {
  // 1. 네비게이션 & 사이드바
  Folder,
  FolderOpen,
  FolderPlus,
  Search,
  FileText,
  FileCode,
  FileSpreadsheet,
  FilePlus,
  ListTree,
  ChevronRight,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  BookOpen,
  Bookmark,

  // 2. 에디터 서식 & 텍스트 도구
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Code,
  Code2,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Quote,
  List,
  ListOrdered,
  CheckSquare,
  Square,
  Minus,
  Eraser,
  Sparkles,
  Wand2,
  Brush,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Superscript,

  // 3. 미디어 & 확장 객체
  Link,
  Link2,
  Image,
  Video,
  Film,
  Calendar,
  Clock,
  MapPin,
  Map,
  Table,
  Sigma,
  PieChart,
  BarChart,

  // 4. 지식 베이스 & AI 엔진
  Brain,
  Cpu,
  GraduationCap,
  Layers,
  Database,
  Tag,
  ShieldCheck,
  Zap,
  Library,

  // 5. 공통 액션 & 윈도우 UI
  Settings,
  HelpCircle,
  Download,
  Upload,
  Share2,
  Copy,
  Clipboard,
  Trash2,
  Edit2,
  Edit3,
  RefreshCw,
  ExternalLink,
  Maximize2,
  Minimize2,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  X,
  Check,
  AlertCircle,
  AlertTriangle,
  Info,
  Lightbulb,
  Megaphone,
  AlertOctagon,
  Sliders,
  Palette,
  LayoutDashboard,
  LogOut,
  Eye,
  EyeOff,
  Sun,
  Moon,
  Save,
  Undo,
  Redo,
  Home,
  Printer,
  Key,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';

export const Icons = {
  // [1. 네비게이션 & 사이드바]
  Explorer: FolderOpen,
  Folder: Folder,
  FolderOpen: FolderOpen,
  FolderAdd: FolderPlus,
  Search: Search,
  Toc: ListTree,
  Document: FileText,
  FileMarkdown: FileText,
  FileCode: FileCode,
  FileTable: FileSpreadsheet,
  FileAdd: FilePlus,
  ArrowRight: ChevronRight,
  ArrowDown: ChevronDown,
  ArrowLeft: ChevronLeft,
  ArrowUp: ChevronUp,
  Book: BookOpen,
  Bookmark: Bookmark,

  // [2. 에디터 서식 & 텍스트 도구]
  Bold: Bold,
  Italic: Italic,
  Underline: Underline,
  Strikethrough: Strikethrough,
  InlineCode: Code,
  CodeBlock: Code2,
  Heading: Heading,
  Heading1: Heading1,
  Heading2: Heading2,
  Heading3: Heading3,
  Quote: Quote,
  BulletList: List,
  OrderedList: ListOrdered,
  Checklist: CheckSquare,
  Unchecked: Square,
  HorizontalRule: Minus,
  Eraser: Eraser,
  AiAssistant: Sparkles,
  AiMagic: Wand2,
  CleanDoc: Brush,
  AlignLeft: AlignLeft,
  AlignCenter: AlignCenter,
  AlignRight: AlignRight,

  // [3. 미디어 & 확장 객체]
  Link: Link,
  DocLink: Link2,
  Footnote: Superscript,
  Image: Image,
  Video: Video,
  Film: Film,
  DateNow: Calendar,
  Clock: Clock,
  Map: MapPin,
  MapArea: Map,
  Table: Table,
  Math: Sigma,
  Chart: BarChart,
  PieChart: PieChart,

  // [4. 지식 베이스 & AI 엔진]
  Brain: Brain,
  KnowledgeDoc: GraduationCap,
  KnowledgeHub: Database,
  Library: Library,
  AiModel: Cpu,
  Layers: Layers,
  Tag: Tag,
  Verified: ShieldCheck,
  FastSpeed: Zap,
  SlashCommand: Zap,

  // [5. 공통 액션 & 윈도우 UI]
  Settings: Settings,
  Help: HelpCircle,
  Export: Download,
  Import: Upload,
  Share: Share2,
  Copy: Copy,
  Paste: Clipboard,
  Delete: Trash2,
  Rename: Edit2,
  Edit: Edit3,
  Refresh: RefreshCw,
  External: ExternalLink,
  Maximize: Maximize2,
  Minimize: Minimize2,
  CloseSidebar: PanelLeftClose,
  OpenSidebar: PanelLeftOpen,
  ClosePanel: PanelRightClose,
  OpenPanel: PanelRightOpen,
  Close: X,
  Checkmark: Check,
  AlertError: AlertCircle,
  AlertWarning: AlertTriangle,
  AlertInfo: Info,
  AlertTip: Lightbulb,
  AlertImportant: Megaphone,
  AlertCaution: AlertOctagon,
  Filter: Sliders,
  Sliders: Sliders,
  Toolbar: Sliders,
  Palette: Palette,
  Dashboard: LayoutDashboard,
  LogOut: LogOut,
  FloatingToolbar: Sliders,
  Preview: Eye,
  EditOnly: EyeOff,
  ThemeLight: Sun,
  ThemeDark: Moon,
  Save: Save,
  Undo: Undo,
  Redo: Redo,
  Home: Home,
  Print: Printer,
  Key: Key,
  ZoomIn: ZoomIn,
  ZoomOut: ZoomOut,
} as const;

export type IconName = keyof typeof Icons;

/**
 * 🎨 아이콘별 카테고리 고유 컬러 & 3D 테마 프리셋
 * - 선명한 명도 대비 보장 (Light/Dark 고대비 통일)
 * - 듀오톤 채움 및 입체감(Depth) 연출을 위한 중앙 집중식 메타데이터
 */
export interface IconThemeDef {
  color: string;
}

export const ICON_THEMES: Partial<Record<IconName, IconThemeDef>> = {
  // [에디터 서식 도구]
  Bold: { color: 'text-blue-600 dark:text-blue-400' },
  Italic: { color: 'text-indigo-600 dark:text-indigo-400' },
  InlineCode: { color: 'text-amber-600 dark:text-amber-400' },
  CodeBlock: { color: 'text-violet-600 dark:text-violet-400' },
  Underline: { color: 'text-sky-600 dark:text-sky-400' },
  Strikethrough: { color: 'text-rose-500 dark:text-rose-400' },
  Heading: { color: 'text-emerald-600 dark:text-emerald-400' },
  Heading1: { color: 'text-emerald-600 dark:text-emerald-400' },
  Heading2: { color: 'text-emerald-600 dark:text-emerald-400' },
  Heading3: { color: 'text-emerald-600 dark:text-emerald-400' },
  HorizontalRule: { color: 'text-slate-500 dark:text-slate-400' },
  OrderedList: { color: 'text-blue-500 dark:text-blue-400' },
  BulletList: { color: 'text-teal-600 dark:text-teal-400' },
  Quote: { color: 'text-purple-600 dark:text-purple-400' },
  Checklist: { color: 'text-emerald-600 dark:text-emerald-400' },
  Eraser: { color: 'text-rose-600 dark:text-rose-400' },
  CleanDoc: { color: 'text-cyan-600 dark:text-cyan-400' },
  AiAssistant: { color: 'text-purple-600 dark:text-purple-400' },
  AiMagic: { color: 'text-violet-600 dark:text-violet-400' },
  AlignLeft: { color: 'text-blue-600 dark:text-blue-400' },
  AlignCenter: { color: 'text-blue-600 dark:text-blue-400' },
  AlignRight: { color: 'text-blue-600 dark:text-blue-400' },

  // [미디어 & 객체]
  Link: { color: 'text-blue-500 dark:text-blue-400' },
  DocLink: { color: 'text-indigo-600 dark:text-indigo-400' },
  Book: { color: 'text-amber-700 dark:text-amber-500' },
  Footnote: { color: 'text-purple-600 dark:text-purple-400' },
  Image: { color: 'text-emerald-500 dark:text-emerald-400' },
  Video: { color: 'text-rose-600 dark:text-rose-500' },
  Film: { color: 'text-rose-600 dark:text-rose-500' },
  DateNow: { color: 'text-orange-500 dark:text-orange-400' },
  Clock: { color: 'text-amber-500 dark:text-amber-400' },
  Map: { color: 'text-teal-600 dark:text-teal-400' },
  MapArea: { color: 'text-teal-600 dark:text-teal-400' },
  Table: { color: 'text-blue-600 dark:text-blue-400' },
  Math: { color: 'text-fuchsia-600 dark:text-fuchsia-400' },

  // [알림 인용구 옵션]
  AlertInfo: { color: 'text-blue-500 dark:text-blue-400' },
  AlertTip: { color: 'text-emerald-600 dark:text-emerald-400' },
  AlertImportant: { color: 'text-purple-600 dark:text-purple-400' },
  AlertWarning: { color: 'text-amber-600 dark:text-amber-400' },
  AlertCaution: { color: 'text-rose-600 dark:text-rose-400' },

  // [네비게이션 & 사이드바]
  Explorer: { color: 'text-amber-500 dark:text-amber-400' },
  Folder: { color: 'text-amber-500 dark:text-amber-400' },
  FolderOpen: { color: 'text-amber-500 dark:text-amber-400' },
  FolderAdd: { color: 'text-amber-500 dark:text-amber-400' },
  Search: { color: 'text-blue-500 dark:text-blue-400' },
  Toc: { color: 'text-indigo-500 dark:text-indigo-400' },
  Document: { color: 'text-blue-500 dark:text-blue-400' },
  FileMarkdown: { color: 'text-blue-500 dark:text-blue-400' },
  FileCode: { color: 'text-purple-500 dark:text-purple-400' },
  FileTable: { color: 'text-emerald-500 dark:text-emerald-400' },
  Brain: { color: 'text-purple-600 dark:text-purple-400' },
  Library: { color: 'text-teal-600 dark:text-teal-400' },
};
