export const helpItems = [
  {
    "id": "help_0",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/00_시작하기.md",
    "file_name": "00_시작하기.md",
    "source_title": "00_시작하기",
    "source_id": "help/00_시작하기.md",
    "source_file": "frontend/public/help/00_시작하기.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_1",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/01_마크다운에디트란.md",
    "file_name": "01_마크다운에디트란.md",
    "source_title": "순서 없는 목록 (글머리 기호)",
    "source_id": "help/01_마크다운에디트란.md",
    "source_file": "frontend/public/help/01_마크다운에디트란.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_2",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/02_에디터-기본.md",
    "file_name": "02_에디터-기본.md",
    "source_title": "02_에디터-기본",
    "source_id": "help/02_에디터-기본.md",
    "source_file": "frontend/public/help/02_에디터-기본.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_3",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/02_온리비_환경_설정_완벽_가이드.md",
    "file_name": "02_온리비_환경_설정_완벽_가이드.md",
    "source_title": "📋 네이버 블로그 포스팅용 최종 원고 (복사용)",
    "source_id": "help/02_온리비_환경_설정_완벽_가이드.md",
    "source_file": "frontend/public/help/02_온리비_환경_설정_완벽_가이드.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_4",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/03_파일-관리.md",
    "file_name": "03_파일-관리.md",
    "source_title": "03_파일-관리",
    "source_id": "help/03_파일-관리.md",
    "source_file": "frontend/public/help/03_파일-관리.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_5",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/04_미리보기-모드.md",
    "file_name": "04_미리보기-모드.md",
    "source_title": "04_미리보기-모드",
    "source_id": "help/04_미리보기-모드.md",
    "source_file": "frontend/public/help/04_미리보기-모드.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_6",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/05_서식-정의.md",
    "file_name": "05_서식-정의.md",
    "source_title": "🎨 서식 정의 및 서식 관리 센터 가이드",
    "source_id": "help/05_서식-정의.md",
    "source_file": "frontend/public/help/05_서식-정의.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_7",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/06_내보내기.md",
    "file_name": "06_내보내기.md",
    "source_title": "06_내보내기",
    "source_id": "help/06_내보내기.md",
    "source_file": "frontend/public/help/06_내보내기.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_8",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/07_표-체크리스트.md",
    "file_name": "07_표-체크리스트.md",
    "source_title": "07_표-체크리스트",
    "source_id": "help/07_표-체크리스트.md",
    "source_file": "frontend/public/help/07_표-체크리스트.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_9",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/08_다이어그램-수식.md",
    "file_name": "08_다이어그램-수식.md",
    "source_title": "08_다이어그램-수식",
    "source_id": "help/08_다이어그램-수식.md",
    "source_file": "frontend/public/help/08_다이어그램-수식.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_10",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/09_슬래시-명령어.md",
    "file_name": "09_슬래시-명령어.md",
    "source_title": "09_슬래시-명령어",
    "source_id": "help/09_슬래시-명령어.md",
    "source_file": "frontend/public/help/09_슬래시-명령어.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_11",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/10_한글-입력.md",
    "file_name": "10_한글-입력.md",
    "source_title": "10_한글-입력",
    "source_id": "help/10_한글-입력.md",
    "source_file": "frontend/public/help/10_한글-입력.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_12",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/11_미디어-삽입.md",
    "file_name": "11_미디어-삽입.md",
    "source_title": "11_미디어-삽입",
    "source_id": "help/11_미디어-삽입.md",
    "source_file": "frontend/public/help/11_미디어-삽입.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_13",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/12_내보내기-고급.md",
    "file_name": "12_내보내기-고급.md",
    "source_title": "12_내보내기-고급",
    "source_id": "help/12_내보내기-고급.md",
    "source_file": "frontend/public/help/12_내보내기-고급.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_14",
    "category": "HELP",
    "category_name": "도움말 문서",
    "url": "/help/13_설정.md",
    "file_name": "13_설정.md",
    "source_title": "13_설정",
    "source_id": "help/13_설정.md",
    "source_file": "frontend/public/help/13_설정.md",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_15",
    "category": "HELP",
    "category_name": "도움말 이미지",
    "url": "/help/assets/fig1_setup_steps.png",
    "file_name": "fig1_setup_steps.png",
    "source_title": "fig1_setup_steps",
    "source_id": "help/assets/fig1_setup_steps.png",
    "source_file": "frontend/public/help/assets/fig1_setup_steps.png",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_16",
    "category": "HELP",
    "category_name": "도움말 이미지",
    "url": "/help/assets/fig2_settings_modal.png",
    "file_name": "fig2_settings_modal.png",
    "source_title": "fig2_settings_modal",
    "source_id": "help/assets/fig2_settings_modal.png",
    "source_file": "frontend/public/help/assets/fig2_settings_modal.png",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_17",
    "category": "HELP",
    "category_name": "도움말 이미지",
    "url": "/help/assets/fig3_dashboard_pricing.png",
    "file_name": "fig3_dashboard_pricing.png",
    "source_title": "fig3_dashboard_pricing",
    "source_id": "help/assets/fig3_dashboard_pricing.png",
    "source_file": "frontend/public/help/assets/fig3_dashboard_pricing.png",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_18",
    "category": "HELP",
    "category_name": "도움말 이미지",
    "url": "/help/assets/fig4_resource_folder.png",
    "file_name": "fig4_resource_folder.png",
    "source_title": "fig4_resource_folder",
    "source_id": "help/assets/fig4_resource_folder.png",
    "source_file": "frontend/public/help/assets/fig4_resource_folder.png",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_19",
    "category": "HELP",
    "category_name": "도움말 이미지",
    "url": "/help/assets/fig5_ai_integration.png",
    "file_name": "fig5_ai_integration.png",
    "source_title": "fig5_ai_integration",
    "source_id": "help/assets/fig5_ai_integration.png",
    "source_file": "frontend/public/help/assets/fig5_ai_integration.png",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  },
  {
    "id": "help_20",
    "category": "HELP",
    "category_name": "도움말 이미지",
    "url": "/help/assets/fig6_css_gallery.png",
    "file_name": "fig6_css_gallery.png",
    "source_title": "fig6_css_gallery",
    "source_id": "help/assets/fig6_css_gallery.png",
    "source_file": "frontend/public/help/assets/fig6_css_gallery.png",
    "author": "Onrivi",
    "created_at": null,
    "source_type": "help",
    "read_only": true
  }
];
